name: Deploy Pages

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed
    branches: [master, next-docs]
  release:
    types: [published, created, edited, unpublished, deleted, released]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:

  build-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Build Package Version Listing
        run: |
          rm package.json
          npm install --no-save got@12.5.3
          git checkout package.json
          node .scripts/create_index_json.mjs kurotu/VRCQuestTools package.json > index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: repo
          path: index.json

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: Website~/package-lock.json
      - run: cd Website~ && npm ci
      - run: cp CHANGELOG.md Website~/docs/changelog.md
      - run: cp CHANGELOG_JP.md Website~/i18n/ja/docusaurus-plugin-content-docs/current/changelog.md
      - run: cd Website~ && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: Website~/build

  build-next-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: next-docs
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: Website~/package-lock.json
      - run: cd Website~ && npm ci
      - run: cp CHANGELOG.md Website~/docs/changelog.md
      - run: cp CHANGELOG_JP.md Website~/i18n/ja/docusaurus-plugin-content-docs/current/changelog.md
      - run: sed -i "s|'/VRCQuestTools/'|'/VRCQuestTools/next/'|" Website~/docusaurus.config.js
      - run: cd Website~ && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: next-docs
          path: Website~/build

  deploy:
    needs: [build-repo, build-docs, build-next-docs]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: repo
          path: ${{env.listPublishDirectory}}

      - uses: actions/download-artifact@v1
        with:
          name: docs
          path: ${{env.listPublishDirectory}}

      - uses: actions/download-artifact@v1
        with:
          name: next-docs
          path: ${{env.listPublishDirectory}}/next

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{env.listPublishDirectory}}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
