name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (like 1.0.0)'
        required: true

jobs:
  bump:
    env:
      TZ: Asia/Tokyo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Make release commit and push it
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ./scripts/bump.sh ${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
          git push

  update-docs:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: latest-docs
          token: ${{ secrets.PAT }}
      - name: Fetch tags
        run: git fetch --prune --unshallow --tags
      - name: Merge latest release
        run: |
          git merge --ff-only v${{ github.event.inputs.version }}
          git push
